#!/usr/bin/env python3
"""Generate CATALOG.md and CATALOG.zh-CN.md: one table per category, built from the READMEs.

  gen_catalog.py            write both catalogues
  gen_catalog.py --check    fail if either is out of date (used in CI)

The README stays a plain awesome list, because awesome-lint and `l0_check.py readme` require that shape.
The catalogue is the same entries as sortable-looking tables, regenerated from the list so the two cannot drift.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENTRY = re.compile(r"^- \[([^\]]+)\]\((https?://[^)\s]+)\) - (.+)$")
HEADING = re.compile(r"^(#{2,3}) (.+)$")
# trailing "(official · coll · ★1.2k · 2026-09)" or "(★12 · stale since 2025-05)"
TAIL = re.compile(r"\s*\(([^()]*(?:★|stale since)[^()]*)\)\s*$")
TEXT = {
    "en": {
        "title": "# Catalogue: every category as a table\n",
        "switch": "*English · [简体中文](CATALOG.zh-CN.md)*\n",
        "intro": ("Every entry of the [README](README.md), one table per category. Generated by "
                  "`scripts/gen_catalog.py`; edit the README, not this file. Badges (`L0`, `L1`, `L2 ×N`, `ΔPass`) "
                  "and what they require are explained in [EVALS.md](EVALS.md) — as of this snapshot no skill has "
                  "passed, so the tag column carries only source tags.\n"),
        "cols": ("| Entry | What it is | Tags | ★ | Updated |\n|---|---|---|---|---|\n"),
        "count": "{n} entries.",
        "toc": "## Contents\n",
    },
    "zh": {
        "title": "# 分类目录：每类硬件一张表\n",
        "switch": "*[English](CATALOG.md) · 简体中文*\n",
        "intro": ("[README](README.zh-CN.md) 的全部条目，每个分类一张表。由 `scripts/gen_catalog.py` 生成；"
                  "要改内容请改 README，不要改本文件。徽章（`L0`、`L1`、`L2 ×N`、`ΔPass`）的含义见 "
                  "[EVALS.zh-CN.md](EVALS.zh-CN.md)——截至本次快照还没有 Skill 通过，所以标签列只有来源标签。\n"),
        "cols": ("| 条目 | 是什么 | 标签 | ★ | 更新 |\n|---|---|---|---|---|\n"),
        "count": "共 {n} 条。",
        "toc": "## 目录\n",
    },
}


def slug(text: str) -> str:
    """GitHub heading anchor."""
    s = text.strip().lower()
    s = re.sub(r"[^\w一-鿿\s-]", "", s)
    return "".join("-" if ch.isspace() else ch for ch in s)


def cell(text: str) -> str:
    return text.replace("|", "\\|").strip()


def parse(readme: Path) -> list[tuple[str, str, list[tuple[str, str, str, str, str, str]]]]:
    """-> [(level, title, [(name, url, desc, tags, stars, updated), ...]), ...]"""
    sections: list[tuple[str, str, list]] = []
    for line in readme.read_text().split("\n"):
        h = HEADING.match(line)
        if h:
            sections.append((h.group(1), h.group(2).strip(), []))
            continue
        m = ENTRY.match(line)
        if not m or not sections:
            continue
        name, url, desc = m.group(1), m.group(2), m.group(3)
        tags = stars = updated = ""
        t = TAIL.search(desc)
        if t:
            desc = desc[: t.start()].rstrip()
            parts = [p.strip() for p in t.group(1).split("·")]
            for p in parts:
                if p.startswith("★"):
                    stars = p[1:]
                elif re.fullmatch(r"\d{4}-\d{2}", p) or p.startswith("stale since"):
                    updated = p
                else:
                    tags = f"{tags}, {p}" if tags else p
        sections[-1][2].append((name, url, desc, tags, stars, updated))
    return sections


def render(readme: Path, lang: str) -> str:
    t = TEXT[lang]
    parsed = parse(readme)
    keep = []
    for i, (level, title, rows) in enumerate(parsed):
        has_child = level == "##" and any(l == "###" and r for l, _, r in parsed[i + 1:i + 2])
        if rows or has_child:
            keep.append((level, title, rows))
    out = [t["title"].rstrip("\n"), "", t["switch"].rstrip("\n"), "", t["intro"].rstrip("\n"), "",
           t["toc"].rstrip("\n")]
    for level, title, rows in keep:
        indent = "" if level == "##" else "  "
        count = f" ({len(rows)})" if rows else ""
        out.append(f"{indent}- [{title}](#{slug(title)}){count}")
    out.append("")
    for level, title, rows in keep:
        out.append(f"{level} {title}")
        out.append("")
        if not rows:
            continue
        out.append(t["count"].format(n=len(rows)))
        out.append("")
        out.append(t["cols"].rstrip("\n"))
        for name, url, desc, tags, stars, updated in rows:
            out.append(f"| [{cell(name)}]({url}) | {cell(desc)} | {cell(tags)} | {cell(stars)} | {cell(updated)} |")
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def main() -> int:
    check = "--check" in sys.argv
    stale = []
    for readme, target, lang in [(ROOT / "README.md", ROOT / "CATALOG.md", "en"),
                                 (ROOT / "README.zh-CN.md", ROOT / "CATALOG.zh-CN.md", "zh")]:
        text = render(readme, lang)
        if check:
            if not target.exists() or target.read_text() != text:
                stale.append(target.name)
        else:
            target.write_text(text)
            print(f"wrote {target.name}: {text.count('| [')} rows")
    if check:
        for name in stale:
            print(f"::error::{name} is out of date — run python scripts/gen_catalog.py")
        print("catalogues up to date" if not stale else "")
        return 1 if stale else 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
